version: '3.7'
services:
  # master
  redis1:
    image: redis:latest
    expose:
      # redis node normal port
      - 6379
    command: redis-server
    networks:
      redis-sentinel-net:
        ipv4_address: 172.22.1.10

  sentinel1:
    image: redis:latest
    expose:
      # redis sentinel normal port
      - 26379
    volumes:
      # volume 标准
      - ./.sentinel1.conf:/etc/sentinel.conf
    command: redis-server /etc/sentinel.conf --sentinel
    networks:
      redis-sentinel-net:
        ipv4_address: 172.22.1.11

  redis2:
    image: redis:latest
    expose:
      - 6379
    command: redis-server --slaveof redis1 6379
    networks:
      redis-sentinel-net:
        ipv4_address: 172.22.1.20

  sentinel2:
    image: redis:latest
    expose:
      - 26379
    volumes:
      - ./.sentinel2.conf:/etc/sentinel.conf
    command: redis-server /etc/sentinel.conf --sentinel
    networks:
      redis-sentinel-net:
        ipv4_address: 172.22.1.21

  redis3:
    image: redis:latest
    expose:
      - 6379
    command: redis-server --slaveof redis1 6379
    networks:
      redis-sentinel-net:
        ipv4_address: 172.22.1.30

  sentinel3:
    image: redis:latest
    expose:
      - 26379
    volumes:
      - ./.sentinel3.conf:/etc/sentinel.conf
    command: redis-server /etc/sentinel.conf --sentinel
    networks:
      redis-sentinel-net:
        ipv4_address: 172.22.1.31

networks:
  redis-sentinel-net:
    driver: bridge
    #external: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
